### ISSUE TITLE
issue on iOS on demo page

### ISSUE THREAD

**Issue by vibe9** [CodyHouse/cd-tooltip-changelog#1]
Having an issue in iOS (iphone x Safari and Chrome), when you tap on a tooltip trigger it works on the first item but does not work (i.e. tooltip does not show at all) when you click on subsequent items. Reproducible using the demo page on the codyhouse website.

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up. We have pushed an updated version of the component that should fix this issue. You can check the updated demo:
https://codyhouse.co/ds/components/app/tooltip

Cheers!
